---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for EC2 Instance

Resources:
  JoelsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Sub ${EC2AmiId}
      InstanceType: !Sub ${InstanceType}
      SubnetId: subnet-0156d42d4eb9ed5ba
      KeyName: joels-key-pair
      Tags:
#        - Key: Application
#          Value:
#            Ref: 'AWS::EC2::Instance'
        - Key: Name
          Value: joels-instance
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.4
Parameters:
  EC2AmiId:
    Type: String
    Description: What VM Image ID
  InstanceType:
    Type: String
    Description: What Instance Type
Outputs:
  JoelsInstance:
    Description: Joels Virtual Private Cloud.
    Value: !Ref JoelsInstance
#  JoelsPrivateIPAddress:
#    Description: Joels Subnet for the VPC
#    Value: !Ref JoelsSubnet
