---
AWSTemplateFormatVersion: '2010-09-09'
Description: joel.webb.labs stelligent-u-04 4.1

Resources:
  JoelsVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: ${Network}/16
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.1
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: ${Network}/24
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
Outputs:
  JoelsVPC:
    Description: Joels Virtual Private Cloud.
    Value: !Ref JoelsVPC
#  MyStacksVPCID:
#    Value: !Ref "AWS::VpcId"
  MyStacksRegion:
    Value: !Ref "AWS::Region"
  AccountId:
    Value: !Ref "AWS::AccountId"
