---
AWSTemplateFormatVersion: '2010-09-09'
Description: joel.webb.labs stelligent-u-04 4.1

Resources:
  JoelsVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Sub ${Network}/16
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-vpc
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.2
  JoelsPrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: JoelsVPC
      CidrBlock: !Sub ${Network}/24
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-private-subnet
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.2
  JoelsInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-internetgateway
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.6
  JoelsAttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId:
        Ref: JoelsVPC
      InternetGatewayId:
        Ref: JoelsInternetGateway
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      ConnectivityType: public
      SubnetId: !Ref JoelsPrivateSubnet
      Tags:
        - Key: Name
          Value: joels-nat-gateway
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.7
#  GWIPAddress:
#    Type: 'AWS::EC2::EIP'
#    Properties:
#      Domain: vpc
#      InstanceId:
#        Ref: NatGateway
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: joel.webb-eip-gateway-nat
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.7
  JoelsRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: JoelsVPC
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-routetable
  Route:
    Type: 'AWS::EC2::Route'
    DependsOn: JoelsAttachGateway
    Properties:
      RouteTableId:
        Ref: JoelsRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: JoelsInternetGateway
  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId:
        Ref: JoelsPrivateSubnet
      RouteTableId:
        Ref: JoelsRouteTable
  NetworkAcl:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId:
        Ref: JoelsVPC
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
  InboundSSHNetworkAclEntry:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '101'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '22'
        To: '22'
  InboundResponsePortsNetworkAclEntry:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '102'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '1024'
        To: '65535'
  SubnetNetworkAclAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId:
        Ref: JoelsPrivateSubnet
      NetworkAclId:
        Ref: NetworkAcl
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId:
        Ref: JoelsVPC
      GroupDescription: Enable SSH access via port 22
      GroupName: joelsSecurityGroup-sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow icmp
          FromPort: 8
          IpProtocol: icmp
          ToPort: -1
        - CidrIp: 0.0.0.0/0
          Description: Allow ssh
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  OutBoundResponsePortsNetworkAclEntry:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAcl
      RuleNumber: '102'
      Protocol: '6'
      RuleAction: allow
      Egress: 'true'
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '1024'
        To: '65535'
Parameters:
  Network:
    Type: String
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Outputs:
  JoelsVPC:
    Description: Joels Virtual Private Cloud.
    Value: !Ref JoelsVPC
    Export:
      Name: JoelsVPC
  JoelsPrivateSubnet:
    Description: Joels Private Subnet for the VPC
    Value: !Ref JoelsPrivateSubnet
    Export:
      Name: JoelsPrivateSubnet
  InstanceSecurityGroup:
    Description: Joels Security Group
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: InstanceSecurityGroup
  NatGateway:
    Description: The NAT Gateway
    Value: !Ref NatGateway
    Export:
      Name: NatGateway
#  MyStacksVPCID:
#    Value: !Ref "AWS::VpcId"
#  MyStacksVPC:
#    Value: !Ref "AWS::EC2::VPC"
#  MyStacksSubnetId:
#    Value: !Ref "AWS::EC2::Subnet"
  MyStacksRegion:
    Value: !Ref "AWS::Region"
  AccountId:
    Value: !Ref "AWS::AccountId"
