---
AWSTemplateFormatVersion: '2010-09-09'
Description: joel.webb.labs stelligent-u-04 4.1

Resources:
  JoelsVPC2:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Sub ${Network}
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-vpc2
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.2
  JoelsPrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: JoelsVPC2
      CidrBlock: !Sub ${Network}/24
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
        - Key: Name
          Value: joels-private-subnet2
        - Key: user
          Value: joel.webb.labs
        - Key: stelligent-u-lesson
          Value: 4.1
        - Key: stelligent-u-lab
          Value: 4.1.2
  # JoelsRouteTable2:
  #   Type: 'AWS::EC2::RouteTable'
  #   Properties:
  #     VpcId:
  #       Ref: JoelsVPC2
  #     Tags:
  #       - Key: Application
  #         Value:
  #           Ref: 'AWS::StackId'
  #       - Key: Name
  #         Value: joels-routetable2
  # Route:
  #   Type: 'AWS::EC2::Route'
  #   Properties:
  #     RouteTableId:
  #       Ref: JoelsRouteTable2
  #     DestinationCidrBlock: 0.0.0.0/0
  # SubnetRouteTableAssociation:
  #   Type: 'AWS::EC2::SubnetRouteTableAssociation'
  #   Properties:
  #     SubnetId:
  #       Ref: JoelsPrivateSubnet2
  #     RouteTableId:
  #       Ref: JoelsRouteTable2
  NetworkAcl2:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId:
        Ref: JoelsVPC2
      Tags:
        - Key: Application
          Value:
            Ref: 'AWS::StackId'
  InboundSSHNetworkAclEntry:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId:
        Ref: NetworkAcl2
      RuleNumber: '101'
      Protocol: '6'
      RuleAction: allow
      Egress: 'false'
      CidrBlock:
        - !Sub ${Network}
        - !Sub ${OtherNetwork}
      PortRange:
        From: '22'
        To: '22'
  InstanceSecurityGroup2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId:
        Ref: JoelsVPC2
      GroupDescription: Enable SSH access via port 22
      GroupName: joelsSecurityGroup2-sg
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow icmp
          FromPort: 8
          IpProtocol: icmp
          ToPort: -1
        - CidrIp: 0.0.0.0/0
          Description: Allow ssh
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: Name
          Value: joelsSecurityGroup2-sg
Parameters:
  Network:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  SSHLocation:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  OtherNetwork:
    Description: ' The IP address range that can be used to SSH to the EC2 instances'
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Outputs:
  JoelsVPC2:
    Description: Joels Virtual Private Cloud.
    Value: !Ref JoelsVPC2
    Export:
      Name: JoelsVPC
  JoelsPrivateSubnet2:
    Description: Joels Private Subnet for the VPC
    Value: !Ref JoelsPrivateSubnet2
    Export:
      Name: JoelsPrivateSubnet2
  InstanceSecurityGroup2:
    Description: Joels Security Group
    Value: !Ref InstanceSecurityGroup2
    Export:
      Name: InstanceSecurityGroup2
  MyStacksRegion:
    Value: !Ref "AWS::Region"
  AccountId:
    Value: !Ref "AWS::AccountId"
