---
AWSTemplateFormatVersion: '2010-09-09'
Resources:  
  MyLambda:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Type: AWS::Lambda::Function
    Properties:
      Handler: echo.lambda_handler
      #Code: code/
      Code:
        S3Bucket: 'joels-stelligent-u-9.1.3'
        S3Key: 'echo.zip'
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: python3.9

  MyLambdaExecutionRole:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonS3ObjectLambdaExecutionRolePolicy

  ApiGatewayIamRole:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: 'Allow'
            Principal:
              Service:
                - 'apigateway.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt MyLambda.Arn
  
  MyApiGatewayRestApi:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
    Type: AWS::ApiGateway::RestApi
    Properties: 
      Name: JoelsApiGateway
  
  MyApiGatewayMethod:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html
    Type: AWS::ApiGateway::Method
    Properties: 
      HttpMethod: ANY
      Integration: 
        Type: AWS
        Credentials: !GetAtt ApiGatewayIamRole.Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: "200"
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambda.Arn}/invocations"

      OperationName: hello
      ResourceId: !GetAtt MyApiGatewayRestApi.RootResourceId
      RestApiId: !Ref MyApiGatewayRestApi
      MethodResponses:
        - StatusCode: "200"
      AuthorizationType: AWS_IAM
  
  MyLambdaPermission:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:invokeFunction
      FunctionName: !Ref MyLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGatewayRestApi}"
  
  MyDeployment:
    #AWS-DOC http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html
    Type: AWS::ApiGateway::Deployment
    Properties: 
      RestApiId: !Ref MyApiGatewayRestApi
    DependsOn: MyApiGatewayMethod

Outputs:
  RestApiId:
    Value: !Ref MyApiGatewayRestApi
    Export:
      Name: JoelsModule9RestApiId
  ResourceId:
    Value: !GetAtt MyApiGatewayRestApi.RootResourceId
    Export:
      Name: JoelsModule9ApiResourceId
