---
AWSTemplateFormatVersion: '2010-09-09'
Description: App stack for module 12.2

Parameters:
  Employees:
    Type: String
    Default: Joels-Module12-2-2-Employees

Resources:
  # AWS-DOC https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  EmployeesDDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref Employees
      AttributeDefinitions: 
        -
          AttributeName: "ID"
          AttributeType: "S"
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
        -
          AttributeName: "Sales"
          AttributeType: "N"
        -
          AttributeName: "NumberOfSongs"
          AttributeType: "N"
      KeySchema: 
        -
          AttributeName: "ID"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "Sales"
              KeyType: "HASH"
            -
              AttributeName: "Artist"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "NumberOfSongs"
        -
          IndexName: "myGSI2"
          KeySchema:
            -
              AttributeName: "NumberOfSongs"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "Artist"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes:
        -
          IndexName: "myLSI"
          KeySchema:
            -
              AttributeName: "Album"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Artist"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"

  DdbTableRole:
    # AWS-DOC https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - dynamodb.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess

Outputs:
  PartsTableName:
    Value: !Ref EmployeesDDBTable
    Export:
      Name: Joels-12-2-PartsTableName

  PartsTableArn:
    Value: !GetAtt EmployeesDDBTable.Arn
    Export:
      Name: Joels-12-2-PartsTableArn