---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "joels-f-stelligent-u-223"
      AccessControl: "BucketOwnerFullControl"
      Tags:
        - Key: user
          Value: joel.webb
        - Key: module
          Value: "8"
        - Key: "stelligent-u-lesson"
          Value: "8.2.2"