---
AWSTemplateFormatVersion: "2010-09-09"
Description: Read Only Template
Resources:
  JoelsGlobalReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      Description: My Own Policy that uses Native Managed ReadOnly
      # https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html
      ManagedPolicyArns:
        # https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1&skipRegion=true#/policies/arn:aws:iam::aws:policy/ReadOnlyAccess$jsonEditor
        # What they can do
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              # Who can do this
              AWS:
                - arn:aws:iam::324320755747:user/joel.webb.labs
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            #Resource: arn:aws:iam::324320755747:user/joel.webb.labs
  JoelsS3CustomerManagedRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Customer Managed Policy
      # https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html
      # ManagedPolicyArns:
        ## https://us-east-1.console.aws.amazon.com/iam/home#/policies/arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess$jsonEditor
        ## What they can do
        #- arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        #- arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              # Who can do this
              AWS:
                - arn:aws:iam::324320755747:user/joel.webb.labs
              Service:
                - iam.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            #Resource:
            # - arn:aws:iam::324320755747:user/joel.webb.labs
      Policies:
        - PolicyName: JoelsFullS3AccessCustomerManagedPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  # What exactly can they do
                  - "s3:*"
                  - "s3-object-lambda:*"
                Resource:
                  - '*'
        - PolicyName: JoelsReadOnlyS3AccessCustomerManagedPolicyLebowski
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  # What exactly can they do
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3-object-lambda:*"
                Resource:
                  - "arn:aws:s3:::joels-fullaccess-s3-bucket-11-15/lebowski*"
  JoelsMyIamReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: JoelsReadOnlyUser
  S3Bucket1:
    DeletionPolicy: Delete
    Type: 'AWS::S3::Bucket'
    Description: Joels Amazon S3 Read Only Bucket On CloudFormation
    Properties:
      BucketName: joels-fullaccess-s3-bucket-11-15
  S3Bucket2:
    DeletionPolicy: Delete
    Type: 'AWS::S3::Bucket'
    Description: Joels Full acess Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: joels-fullaccess-s3-bucket-11-16
